# Generated by Django 5.0.14 on 2026-05-28 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectoresCriticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sector', models.CharField(help_text='Ej: Deprimido de la 80', max_length=150)),
                ('departamento', models.CharField(choices=[('ANT', 'Antioquia'), ('BGT', 'Bogotá D.C.'), ('VAC', 'Valle del Cauca'), ('SUC', 'SUCRE'), ('COR', 'Córdoba'), ('ATL', 'Atlántico'), ('BOL', 'Bolívar'), ('CAL', 'Caldas'), ('CAQ', 'Caquetá'), ('CAS', 'Casanare'), ('CUN', 'Cundinamarca'), ('HUA', 'Huila'), ('MAG', 'Magdalena'), ('NAR', 'Nariño'), ('QUE', 'Quindío'), ('RIS', 'Risaralda')], db_index=True, default='ANT', help_text='Departamento', max_length=3)),
                ('municipio', models.CharField(db_index=True, default='Medellín', help_text='Ej: Medellín, Bogotá, Bello', max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10, max_length=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11, max_length=11)),
                ('es_inundable', models.BooleanField(default=False, help_text='Sufre inundaciones relámpago')),
                ('capacidad_vehicular_max', models.IntegerField(help_text='Umbral de carros permitidos antes de colapso')),
            ],
            options={
                'verbose_name_plural': 'Sectores Críticos',
                'db_table': 'sectores_criticos',
            },
        ),
        migrations.CreateModel(
            name='ClimaActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(default='ANT', help_text='Código departamento', max_length=3)),
                ('municipio', models.CharField(default='Medellín', help_text='Ej: Medellín, Bogotá', max_length=100)),
                ('intensidad_lluvia', models.FloatField(default=0.0, help_text='Medido en mm/h')),
                ('alerta_inundacion_activa', models.BooleanField(default=False)),
                ('ultima_actualizacion', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Clima Actual',
                'db_table': 'clima_actual',
                'unique_together': {('departamento', 'municipio')},
            },
        ),
        migrations.CreateModel(
            name='PrediccionesTrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ejecucion', models.DateTimeField(help_text='Cuándo calculó la IA la predicción')),
                ('fecha_hora_predicha', models.DateTimeField(db_index=True, help_text='Hora futura anticipada')),
                ('probabilidad_congestion', models.DecimalField(decimal_places=2, help_text='Riesgo entre 0.00 y 1.00', max_digits=3)),
                ('sector', models.ForeignKey(db_column='sector_id', on_delete=django.db.models.deletion.CASCADE, to='core_app.sectorescriticos')),
            ],
            options={
                'verbose_name_plural': 'Predicciones de Tráfico',
                'db_table': 'predicciones_trafico',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAccidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('gravedad', models.CharField(choices=[('Solo Daños', 'Solo Daños'), ('Con Heridos', 'Con Heridos'), ('Con Muertos', 'Con Muertos')], max_length=20)),
                ('tipo_vehiculo', models.CharField(help_text='Moto, Auto, Peatón, Bicicleta', max_length=50)),
                ('condicion_climatica', models.CharField(default='Seco', max_length=50)),
                ('sector', models.ForeignKey(db_column='sector_id', on_delete=django.db.models.deletion.CASCADE, to='core_app.sectorescriticos')),
            ],
            options={
                'verbose_name_plural': 'Historial de Accidentes',
                'db_table': 'historico_accidentes',
            },
        ),
        migrations.CreateModel(
            name='FlujoTiempoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_registro', models.DateTimeField(db_index=True)),
                ('velocidad_promedio', models.FloatField(help_text='Velocidad actual en km/h')),
                ('volumen_vehicular', models.IntegerField(help_text='Cantidad de vehículos detectados')),
                ('nivel_congestion', models.CharField(choices=[('Fluido', 'Fluido'), ('Moderado', 'Moderado'), ('Crítico', 'Crítico')], max_length=20)),
                ('sector', models.ForeignKey(db_column='sector_id', on_delete=django.db.models.deletion.CASCADE, to='core_app.sectorescriticos')),
            ],
            options={
                'verbose_name_plural': 'Flujo en Tiempo Real',
                'db_table': 'flujo_tiempo_real',
            },
        ),
    ]
