# Generated by Django 5.2 on 2026-05-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectoresCriticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sector', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('barrio', models.CharField(blank=True, max_length=50, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('es_inundable', models.BooleanField(default=False)),
                ('capacidad_vehicular_max', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ClimaActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('intensidad_lluvia', models.FloatField()),
                ('alerta_inundacion_activa', models.BooleanField(default=False)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlujoTiempoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_registro', models.DateTimeField()),
                ('velocidad_promedio', models.FloatField()),
                ('volumen_vehicular', models.IntegerField()),
                ('nivel_congestion', models.CharField(choices=[('Fluido', 'Fluido'), ('Moderado', 'Moderado'), ('Crítico', 'Crítico')], max_length=20)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.sectorescriticos')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAccidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('gravedad', models.CharField(choices=[('Solo Daños', 'Solo Daños'), ('Con Heridos', 'Con Heridos'), ('Con Muertos', 'Con Muertos')], max_length=20)),
                ('tipo_vehiculo', models.CharField(max_length=20)),
                ('condicion_climatica', models.CharField(max_length=20)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.sectorescriticos')),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionesTrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ejecucion', models.DateTimeField()),
                ('fecha_hora_predicha', models.DateTimeField()),
                ('probabilidad_congestion', models.FloatField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.sectorescriticos')),
            ],
        ),
    ]